### signup 회원가입
POST {{host}}/api/member/signup
Content-Type: application/json

{
  "name": "name",
  "email": "email@naver.com",
  "password": "password1234",
  "phoneNumber": "01011111111",
  "role": "ADMIN"
}

### signin 로그인
POST {{host}}/api/member/signin
Content-Type: application/json

{
  "email": "email@naver.com",
  "password": "password1234"
}