### create category
POST {{host}}/api/category
Content-Type: application/json
Authorization: Bearer {{$auth.token()}}

{
  "categoryName": "category"
}

### all category
GET {{host}}/api/category
Authorization: Bearer {{$auth.token()}}



### update category
PUT {{host}}/api/category/{{id}}
Content-Type: application/json
Authorization: Bearer {{$auth.token()}}


{
  "categoryName": "updateCategory"
}

### delete category
DELETE {{host}}/api/category/{{id}}
Authorization: Bearer {{$auth.token()}}
