### create post
POST {{host}}/api/post
Content-Type: application/json
Authorization: Bearer {{$auth.token()}}

{
  "title": "title",
  "contents": "contents",
  "categoryName": null,
  "imageId": null
}

### update post
PATCH {{host}}/api/post/{{id}}
Content-Type: application/json
Authorization: Bearer {{$auth.token()}}

{
  "title": "updateTitle",
  "contents": "updateContents",
  "categoryName": null,
  "imageId": null
}

### search post
GET {{host}}/api/post/get/search?keyword={{keyword}}&page=0&size=10

### 전체 post 조회(최신순)
GET {{host}}/api/post/get?page=0&size=10

### post 조회
GET {{host}}/api/post/get/{{id}}

### 이미지 업로드
POST {{host}}/api/post/uploadImage
Content-Type: multipart/form-data; boundary=PersonalBlogProject_7MA4YWxkTrZu0gW
Authorization: Bearer {{$auth.token()}}

--PersonalBlogProject_7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="{{파일 경로}}"

--PersonalBlogProject_7MA4YWxkTrZu0gW--