### create post
POST {{host}}/api/post
Content-Type: application/json
Authorization: Bearer {{$auth.token()}}

{
  "title": "post",
  "contents": "contents",
  "categoryName": null
}

### 전체 post 조회(최신순)
GET {{host}}/api/post/get?page=0&size=1

### post 조회
GET {{host}}/api/post/get/{{id}}

### post update
PATCH {{host}}/api/post/{{id}}
Content-Type: application/json
Authorization: Bearer {{$auth.token()}}

{
  "title": "updateTitile",
  "contents": "updateContents"
}

### delete post
DELETE {{host}}/api/post/{{id}}
Authorization: Bearer {{$auth.token()}}

### search post
GET {{host}}/api/post/get/search?keyword={{keyword}}&page=0&size=1

