server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personal_project?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: NAME
    password: PASSWORD

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  jwt:
    key: YOUR_JWT_KEY
cloud:
  aws:
    s3:

    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: YOUR_ACCESS_KEY
      secretKey: YOUR_SECRET_KEY