server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personal_project?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 9999

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  jwt:
    key: cGVyc29uYWwtcHJvamVjdC1ibG9nLXplcm9iYXNlLXBlcnNvbmFsUHJvamVjdAo=
cloud:
  aws:
    s3:

    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIA3FLDXMDQUSL3I54V
      secretKey: 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